version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    command:
      # API e Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Metrics para Prometheus
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      # Logs
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
      - "8080:8080"   # Dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/certificates
    networks:
      - traefik-public
      - monitoring
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # Dashboard do Traefik
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  webapp:
    image: webapp:latest
    environment:
      - UPLOAD_FOLDER=/app/data
      - FLASK_ENV=production
      - PUID=1000
      - PGID=1000
    volumes:
      - dados_nfs:/app/data
    networks:
      - traefik-public
      - monitoring
    deploy:
      mode: replicated
      replicas: 3  # 3 instâncias para load balancing
      labels:
        # Traefik routing
        - "traefik.enable=true"
        - "traefik.http.routers.webapp.rule=Host(`webapp.localhost`)"
        - "traefik.http.routers.webapp.entrypoints=web"
        - "traefik.http.services.webapp.loadbalancer.server.port=8080"
        # Sticky sessions (importante para autenticação)
        - "traefik.http.services.webapp.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.webapp.loadbalancer.sticky.cookie.name=webapp_sticky"
        # Health check
        - "traefik.http.services.webapp.loadbalancer.healthcheck.path=/health"
        - "traefik.http.services.webapp.loadbalancer.healthcheck.interval=10s"
        # Monitoring labels
        - "com.docker.compose.service=webapp"
        - "app=webapp"
        - "monitoring=true"
      update_config:
        parallelism: 1        # Atualizar 1 container de cada vez
        delay: 10s
        failure_action: rollback
        order: start-first    # Garantir zero-downtime
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0  # Versão específica mais estável
    hostname: cadvisor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys:/sys:ro
    # Remover: privileged e devices não funcionam bem no Docker Desktop macOS
    networks:
      - monitoring
      - traefik-public
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        # Router
        - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.localhost`)"
        - "traefik.http.routers.cadvisor.entrypoints=web"
        # Middleware para adicionar trailing slash (resolve 307)
        - "traefik.http.middlewares.cadvisor-redirect.redirectregex.regex=^(.*)/containers$$"
        - "traefik.http.middlewares.cadvisor-redirect.redirectregex.replacement=$${1}/containers/"
        - "traefik.http.routers.cadvisor.middlewares=cadvisor-redirect"
        # Service
        - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      restart_policy:
        condition: on-failure

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring
    deploy:
      mode: global  # 1 instância por node
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://grafana.localhost
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      restart_policy:
        condition: on-failure
    depends_on:
      - prometheus

volumes:
  dados_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.64.5,nfsvers=4,proto=tcp,rw,noatime"
      device: ":/dados_webapp"
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  traefik-certificates:
    driver: local

networks:
  traefik-public:
    external: true
  monitoring:
    driver: overlay
    attachable: true